{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMTskaW8kryIGT+qj+6nIrD",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/dfukagaw28/ColabNotebooks/blob/main/Colab_%E3%81%A7_iiif_prezi3_%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%A6%E3%81%BF%E3%82%8B.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "# Colab で iiif-prezi3 を使ってみる"
      ],
      "metadata": {
        "id": "YetShq2Q1gAP"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "## まとめ\n",
        "\n",
        "*   [iiif-prezi3](https://iiif-prezi.github.io/iiif-prezi3/) は iiif-prezi の後継で，IIIF Presentation API 3.0 に対応しているらしい\n",
        "*   Colab で iiif-prezi3 を利用しようとすると，インストールエラーが発生する\n",
        "    *   原因はパッケージの依存関係の不整合\n",
        "    *   iiif-prezi3 が要求するのは `pydantic<2.0.0,>=1.9.2`\n",
        "    *   Colab にプリインストールされているパッケージの多くは 2.0 以上を要求する\n",
        "        *   albumentations (>=2.9.2): 機械学習分野で人気の、画像データ拡張ライブラリ\n",
        "        *   google-genai (>=2.0.0): Gemini API を使うためのライブラリ\n",
        "        *   thinc (>=2.0.0): lightweight deep learning library\n",
        "        *   langchain (>=2.7.4), langchain-core (>=2.5.2): LLM 開発のためのライブラリ\n",
        "*   依存関係を書き換えれば，無理やり「インストール」することはできる\n",
        "    *   ただしコードをあちこち書き換えないとテストをパスできない\n",
        "    *   実際に使うこともできない\n",
        "*   問題となるパッケージを削除すれば使える"
      ],
      "metadata": {
        "id": "rC3by3kM1oAH"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "!pip list | grep pydantic"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "40iM-2zeD0-P",
        "outputId": "27ffd6f3-8bdf-4785-a0f0-d625df88c8a3"
      },
      "execution_count": 1,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "pydantic                              2.11.4\n",
            "pydantic_core                         2.33.2\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 2,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "eS__IlUt1bT0",
        "outputId": "e8f5b2ec-53bb-4954-9593-370f9f6f13f8"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Collecting iiif-prezi3\n",
            "  Downloading iiif_prezi3-2.0.1-py3-none-any.whl.metadata (8.0 kB)\n",
            "Collecting pydantic<2.0.0,>=1.9.2 (from iiif-prezi3)\n",
            "  Downloading pydantic-1.10.22-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (154 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m154.1/154.1 kB\u001b[0m \u001b[31m2.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hRequirement already satisfied: requests<3.0.0,>=2.28.0 in /usr/local/lib/python3.11/dist-packages (from iiif-prezi3) (2.32.3)\n",
            "Requirement already satisfied: Pillow<=12.0.0,>=9.1.1 in /usr/local/lib/python3.11/dist-packages (from iiif-prezi3) (11.2.1)\n",
            "Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<2.0.0,>=1.9.2->iiif-prezi3) (4.13.2)\n",
            "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.28.0->iiif-prezi3) (3.4.2)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.28.0->iiif-prezi3) (3.10)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.28.0->iiif-prezi3) (2.4.0)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.28.0->iiif-prezi3) (2025.4.26)\n",
            "Downloading iiif_prezi3-2.0.1-py3-none-any.whl (28 kB)\n",
            "Downloading pydantic-1.10.22-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m3.1/3.1 MB\u001b[0m \u001b[31m36.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hInstalling collected packages: pydantic, iiif-prezi3\n",
            "  Attempting uninstall: pydantic\n",
            "    Found existing installation: pydantic 2.11.4\n",
            "    Uninstalling pydantic-2.11.4:\n",
            "      Successfully uninstalled pydantic-2.11.4\n",
            "\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
            "langchain 0.3.25 requires pydantic<3.0.0,>=2.7.4, but you have pydantic 1.10.22 which is incompatible.\n",
            "google-genai 1.15.0 requires pydantic<3.0.0,>=2.0.0, but you have pydantic 1.10.22 which is incompatible.\n",
            "thinc 8.3.6 requires pydantic<3.0.0,>=2.0.0, but you have pydantic 1.10.22 which is incompatible.\n",
            "albumentations 2.0.6 requires pydantic>=2.9.2, but you have pydantic 1.10.22 which is incompatible.\n",
            "langchain-core 0.3.59 requires pydantic<3.0.0,>=2.5.2; python_full_version < \"3.12.4\", but you have pydantic 1.10.22 which is incompatible.\u001b[0m\u001b[31m\n",
            "\u001b[0mSuccessfully installed iiif-prezi3-2.0.1 pydantic-1.10.22\n"
          ]
        }
      ],
      "source": [
        "!pip install iiif-prezi3"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "## 無理やりインストールしてみる"
      ],
      "metadata": {
        "id": "eW1I1ge3-zWc"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "*   依存関係の設定を書き換えれば「インストール」できる"
      ],
      "metadata": {
        "id": "Q_NnDeVELXdG"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "!pip uninstall -y iiif-prezi3\n",
        "!pip install 'pydantic>=2.0.0,<3.0.0'"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "YUGX7bfN-4C7",
        "outputId": "c6ff50dd-86a0-4b23-f7d1-d65cc9afd994"
      },
      "execution_count": 3,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Found existing installation: iiif-prezi3 2.0.1\n",
            "Uninstalling iiif-prezi3-2.0.1:\n",
            "  Successfully uninstalled iiif-prezi3-2.0.1\n",
            "Collecting pydantic<3.0.0,>=2.0.0\n",
            "  Downloading pydantic-2.11.5-py3-none-any.whl.metadata (67 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m67.2/67.2 kB\u001b[0m \u001b[31m1.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hRequirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3.0.0,>=2.0.0) (0.7.0)\n",
            "Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic<3.0.0,>=2.0.0) (2.33.2)\n",
            "Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.11/dist-packages (from pydantic<3.0.0,>=2.0.0) (4.13.2)\n",
            "Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3.0.0,>=2.0.0) (0.4.0)\n",
            "Downloading pydantic-2.11.5-py3-none-any.whl (444 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m444.2/444.2 kB\u001b[0m \u001b[31m10.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hInstalling collected packages: pydantic\n",
            "  Attempting uninstall: pydantic\n",
            "    Found existing installation: pydantic 1.10.22\n",
            "    Uninstalling pydantic-1.10.22:\n",
            "      Successfully uninstalled pydantic-1.10.22\n",
            "Successfully installed pydantic-2.11.5\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "VERSION = '2.0.1'\n",
        "\n",
        "%cd /content\n",
        "!rm -rf iiif-prezi3\n",
        "!git clone https://github.com/iiif-prezi/iiif-prezi3.git\n",
        "!git checkout {VERSION}\n",
        "\n",
        "%cd /content/iiif-prezi3\n",
        "!echo {VERSION} > version.txt\n",
        "!sed -i 's/\"pydantic >= 1.9.2, <2.0.0\"/\"pydantic >= 1.9.2, <3.0.0\"/g' setup.py\n",
        "!python setup.py install"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "-4hkNk_i1i6W",
        "outputId": "e1ec7c64-312a-4d32-d3df-1cd9f4a81b17"
      },
      "execution_count": 4,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "/content\n",
            "Cloning into 'iiif-prezi3'...\n",
            "remote: Enumerating objects: 4853, done.\u001b[K\n",
            "remote: Counting objects: 100% (673/673), done.\u001b[K\n",
            "remote: Compressing objects: 100% (266/266), done.\u001b[K\n",
            "remote: Total 4853 (delta 373), reused 472 (delta 271), pack-reused 4180 (from 2)\u001b[K\n",
            "Receiving objects: 100% (4853/4853), 2.67 MiB | 5.15 MiB/s, done.\n",
            "Resolving deltas: 100% (2990/2990), done.\n",
            "fatal: not a git repository (or any of the parent directories): .git\n",
            "/content/iiif-prezi3\n",
            "running install\n",
            "/usr/local/lib/python3.11/dist-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.\n",
            "!!\n",
            "\n",
            "        ********************************************************************************\n",
            "        Please avoid running ``setup.py`` directly.\n",
            "        Instead, use pypa/build, pypa/installer or other\n",
            "        standards-based tools.\n",
            "\n",
            "        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.\n",
            "        ********************************************************************************\n",
            "\n",
            "!!\n",
            "  self.initialize_options()\n",
            "/usr/local/lib/python3.11/dist-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.\n",
            "!!\n",
            "\n",
            "        ********************************************************************************\n",
            "        Please avoid running ``setup.py`` and ``easy_install``.\n",
            "        Instead, use pypa/build, pypa/installer or other\n",
            "        standards-based tools.\n",
            "\n",
            "        See https://github.com/pypa/setuptools/issues/917 for details.\n",
            "        ********************************************************************************\n",
            "\n",
            "!!\n",
            "  self.initialize_options()\n",
            "running bdist_egg\n",
            "running egg_info\n",
            "creating iiif_prezi3.egg-info\n",
            "writing iiif_prezi3.egg-info/PKG-INFO\n",
            "writing dependency_links to iiif_prezi3.egg-info/dependency_links.txt\n",
            "writing requirements to iiif_prezi3.egg-info/requires.txt\n",
            "writing top-level names to iiif_prezi3.egg-info/top_level.txt\n",
            "writing manifest file 'iiif_prezi3.egg-info/SOURCES.txt'\n",
            "reading manifest file 'iiif_prezi3.egg-info/SOURCES.txt'\n",
            "adding license file 'LICENSE'\n",
            "writing manifest file 'iiif_prezi3.egg-info/SOURCES.txt'\n",
            "installing library code to build/bdist.linux-x86_64/egg\n",
            "running install_lib\n",
            "running build_py\n",
            "creating build/lib/iiif_prezi3\n",
            "copying iiif_prezi3/base.py -> build/lib/iiif_prezi3\n",
            "copying iiif_prezi3/loader.py -> build/lib/iiif_prezi3\n",
            "copying iiif_prezi3/__init__.py -> build/lib/iiif_prezi3\n",
            "copying iiif_prezi3/skeleton.py -> build/lib/iiif_prezi3\n",
            "creating build/lib/iiif_prezi3/helpers\n",
            "copying iiif_prezi3/helpers/set_hwd_from_file.py -> build/lib/iiif_prezi3/helpers\n",
            "copying iiif_prezi3/helpers/create_canvas_from_iiif.py -> build/lib/iiif_prezi3/helpers\n",
            "copying iiif_prezi3/helpers/add_label.py -> build/lib/iiif_prezi3/helpers\n",
            "copying iiif_prezi3/helpers/auto_fields.py -> build/lib/iiif_prezi3/helpers\n",
            "copying iiif_prezi3/helpers/make_canvas.py -> build/lib/iiif_prezi3/helpers\n",
            "copying iiif_prezi3/helpers/make_range.py -> build/lib/iiif_prezi3/helpers\n",
            "copying iiif_prezi3/helpers/add_metadata.py -> build/lib/iiif_prezi3/helpers\n",
            "copying iiif_prezi3/helpers/set_hwd.py -> build/lib/iiif_prezi3/helpers\n",
            "copying iiif_prezi3/helpers/make_manifest.py -> build/lib/iiif_prezi3/helpers\n",
            "copying iiif_prezi3/helpers/annotation_helpers.py -> build/lib/iiif_prezi3/helpers\n",
            "copying iiif_prezi3/helpers/make_service.py -> build/lib/iiif_prezi3/helpers\n",
            "copying iiif_prezi3/helpers/add_item.py -> build/lib/iiif_prezi3/helpers\n",
            "copying iiif_prezi3/helpers/make_collection.py -> build/lib/iiif_prezi3/helpers\n",
            "copying iiif_prezi3/helpers/add_service.py -> build/lib/iiif_prezi3/helpers\n",
            "copying iiif_prezi3/helpers/to_reference.py -> build/lib/iiif_prezi3/helpers\n",
            "copying iiif_prezi3/helpers/add_thumbnail.py -> build/lib/iiif_prezi3/helpers\n",
            "copying iiif_prezi3/helpers/canvas_sizes.py -> build/lib/iiif_prezi3/helpers\n",
            "copying iiif_prezi3/helpers/__init__.py -> build/lib/iiif_prezi3/helpers\n",
            "copying iiif_prezi3/helpers/add_range.py -> build/lib/iiif_prezi3/helpers\n",
            "copying iiif_prezi3/helpers/add_image.py -> build/lib/iiif_prezi3/helpers\n",
            "copying iiif_prezi3/helpers/set_hwd_from_iiif.py -> build/lib/iiif_prezi3/helpers\n",
            "creating build/lib/iiif_prezi3/extensions\n",
            "copying iiif_prezi3/extensions/example_extension.py -> build/lib/iiif_prezi3/extensions\n",
            "copying iiif_prezi3/extensions/__init__.py -> build/lib/iiif_prezi3/extensions\n",
            "creating build/lib/iiif_prezi3/config\n",
            "copying iiif_prezi3/config/config.py -> build/lib/iiif_prezi3/config\n",
            "copying iiif_prezi3/config/__init__.py -> build/lib/iiif_prezi3/config\n",
            "copying iiif_prezi3/config/extensions.json -> build/lib/iiif_prezi3/config\n",
            "creating build/bdist.linux-x86_64/egg\n",
            "creating build/bdist.linux-x86_64/egg/iiif_prezi3\n",
            "creating build/bdist.linux-x86_64/egg/iiif_prezi3/helpers\n",
            "copying build/lib/iiif_prezi3/helpers/set_hwd_from_file.py -> build/bdist.linux-x86_64/egg/iiif_prezi3/helpers\n",
            "copying build/lib/iiif_prezi3/helpers/create_canvas_from_iiif.py -> build/bdist.linux-x86_64/egg/iiif_prezi3/helpers\n",
            "copying build/lib/iiif_prezi3/helpers/add_label.py -> build/bdist.linux-x86_64/egg/iiif_prezi3/helpers\n",
            "copying build/lib/iiif_prezi3/helpers/auto_fields.py -> build/bdist.linux-x86_64/egg/iiif_prezi3/helpers\n",
            "copying build/lib/iiif_prezi3/helpers/make_canvas.py -> build/bdist.linux-x86_64/egg/iiif_prezi3/helpers\n",
            "copying build/lib/iiif_prezi3/helpers/make_range.py -> build/bdist.linux-x86_64/egg/iiif_prezi3/helpers\n",
            "copying build/lib/iiif_prezi3/helpers/add_metadata.py -> build/bdist.linux-x86_64/egg/iiif_prezi3/helpers\n",
            "copying build/lib/iiif_prezi3/helpers/set_hwd.py -> build/bdist.linux-x86_64/egg/iiif_prezi3/helpers\n",
            "copying build/lib/iiif_prezi3/helpers/make_manifest.py -> build/bdist.linux-x86_64/egg/iiif_prezi3/helpers\n",
            "copying build/lib/iiif_prezi3/helpers/annotation_helpers.py -> build/bdist.linux-x86_64/egg/iiif_prezi3/helpers\n",
            "copying build/lib/iiif_prezi3/helpers/make_service.py -> build/bdist.linux-x86_64/egg/iiif_prezi3/helpers\n",
            "copying build/lib/iiif_prezi3/helpers/add_item.py -> build/bdist.linux-x86_64/egg/iiif_prezi3/helpers\n",
            "copying build/lib/iiif_prezi3/helpers/make_collection.py -> build/bdist.linux-x86_64/egg/iiif_prezi3/helpers\n",
            "copying build/lib/iiif_prezi3/helpers/add_service.py -> build/bdist.linux-x86_64/egg/iiif_prezi3/helpers\n",
            "copying build/lib/iiif_prezi3/helpers/to_reference.py -> build/bdist.linux-x86_64/egg/iiif_prezi3/helpers\n",
            "copying build/lib/iiif_prezi3/helpers/add_thumbnail.py -> build/bdist.linux-x86_64/egg/iiif_prezi3/helpers\n",
            "copying build/lib/iiif_prezi3/helpers/canvas_sizes.py -> build/bdist.linux-x86_64/egg/iiif_prezi3/helpers\n",
            "copying build/lib/iiif_prezi3/helpers/__init__.py -> build/bdist.linux-x86_64/egg/iiif_prezi3/helpers\n",
            "copying build/lib/iiif_prezi3/helpers/add_range.py -> build/bdist.linux-x86_64/egg/iiif_prezi3/helpers\n",
            "copying build/lib/iiif_prezi3/helpers/add_image.py -> build/bdist.linux-x86_64/egg/iiif_prezi3/helpers\n",
            "copying build/lib/iiif_prezi3/helpers/set_hwd_from_iiif.py -> build/bdist.linux-x86_64/egg/iiif_prezi3/helpers\n",
            "copying build/lib/iiif_prezi3/base.py -> build/bdist.linux-x86_64/egg/iiif_prezi3\n",
            "copying build/lib/iiif_prezi3/loader.py -> build/bdist.linux-x86_64/egg/iiif_prezi3\n",
            "copying build/lib/iiif_prezi3/__init__.py -> build/bdist.linux-x86_64/egg/iiif_prezi3\n",
            "creating build/bdist.linux-x86_64/egg/iiif_prezi3/extensions\n",
            "copying build/lib/iiif_prezi3/extensions/example_extension.py -> build/bdist.linux-x86_64/egg/iiif_prezi3/extensions\n",
            "copying build/lib/iiif_prezi3/extensions/__init__.py -> build/bdist.linux-x86_64/egg/iiif_prezi3/extensions\n",
            "creating build/bdist.linux-x86_64/egg/iiif_prezi3/config\n",
            "copying build/lib/iiif_prezi3/config/config.py -> build/bdist.linux-x86_64/egg/iiif_prezi3/config\n",
            "copying build/lib/iiif_prezi3/config/extensions.json -> build/bdist.linux-x86_64/egg/iiif_prezi3/config\n",
            "copying build/lib/iiif_prezi3/config/__init__.py -> build/bdist.linux-x86_64/egg/iiif_prezi3/config\n",
            "copying build/lib/iiif_prezi3/skeleton.py -> build/bdist.linux-x86_64/egg/iiif_prezi3\n",
            "byte-compiling build/bdist.linux-x86_64/egg/iiif_prezi3/helpers/set_hwd_from_file.py to set_hwd_from_file.cpython-311.pyc\n",
            "byte-compiling build/bdist.linux-x86_64/egg/iiif_prezi3/helpers/create_canvas_from_iiif.py to create_canvas_from_iiif.cpython-311.pyc\n",
            "byte-compiling build/bdist.linux-x86_64/egg/iiif_prezi3/helpers/add_label.py to add_label.cpython-311.pyc\n",
            "byte-compiling build/bdist.linux-x86_64/egg/iiif_prezi3/helpers/auto_fields.py to auto_fields.cpython-311.pyc\n",
            "byte-compiling build/bdist.linux-x86_64/egg/iiif_prezi3/helpers/make_canvas.py to make_canvas.cpython-311.pyc\n",
            "byte-compiling build/bdist.linux-x86_64/egg/iiif_prezi3/helpers/make_range.py to make_range.cpython-311.pyc\n",
            "byte-compiling build/bdist.linux-x86_64/egg/iiif_prezi3/helpers/add_metadata.py to add_metadata.cpython-311.pyc\n",
            "byte-compiling build/bdist.linux-x86_64/egg/iiif_prezi3/helpers/set_hwd.py to set_hwd.cpython-311.pyc\n",
            "byte-compiling build/bdist.linux-x86_64/egg/iiif_prezi3/helpers/make_manifest.py to make_manifest.cpython-311.pyc\n",
            "byte-compiling build/bdist.linux-x86_64/egg/iiif_prezi3/helpers/annotation_helpers.py to annotation_helpers.cpython-311.pyc\n",
            "byte-compiling build/bdist.linux-x86_64/egg/iiif_prezi3/helpers/make_service.py to make_service.cpython-311.pyc\n",
            "byte-compiling build/bdist.linux-x86_64/egg/iiif_prezi3/helpers/add_item.py to add_item.cpython-311.pyc\n",
            "byte-compiling build/bdist.linux-x86_64/egg/iiif_prezi3/helpers/make_collection.py to make_collection.cpython-311.pyc\n",
            "byte-compiling build/bdist.linux-x86_64/egg/iiif_prezi3/helpers/add_service.py to add_service.cpython-311.pyc\n",
            "byte-compiling build/bdist.linux-x86_64/egg/iiif_prezi3/helpers/to_reference.py to to_reference.cpython-311.pyc\n",
            "byte-compiling build/bdist.linux-x86_64/egg/iiif_prezi3/helpers/add_thumbnail.py to add_thumbnail.cpython-311.pyc\n",
            "byte-compiling build/bdist.linux-x86_64/egg/iiif_prezi3/helpers/canvas_sizes.py to canvas_sizes.cpython-311.pyc\n",
            "byte-compiling build/bdist.linux-x86_64/egg/iiif_prezi3/helpers/__init__.py to __init__.cpython-311.pyc\n",
            "byte-compiling build/bdist.linux-x86_64/egg/iiif_prezi3/helpers/add_range.py to add_range.cpython-311.pyc\n",
            "byte-compiling build/bdist.linux-x86_64/egg/iiif_prezi3/helpers/add_image.py to add_image.cpython-311.pyc\n",
            "byte-compiling build/bdist.linux-x86_64/egg/iiif_prezi3/helpers/set_hwd_from_iiif.py to set_hwd_from_iiif.cpython-311.pyc\n",
            "byte-compiling build/bdist.linux-x86_64/egg/iiif_prezi3/base.py to base.cpython-311.pyc\n",
            "byte-compiling build/bdist.linux-x86_64/egg/iiif_prezi3/loader.py to loader.cpython-311.pyc\n",
            "byte-compiling build/bdist.linux-x86_64/egg/iiif_prezi3/__init__.py to __init__.cpython-311.pyc\n",
            "byte-compiling build/bdist.linux-x86_64/egg/iiif_prezi3/extensions/example_extension.py to example_extension.cpython-311.pyc\n",
            "byte-compiling build/bdist.linux-x86_64/egg/iiif_prezi3/extensions/__init__.py to __init__.cpython-311.pyc\n",
            "byte-compiling build/bdist.linux-x86_64/egg/iiif_prezi3/config/config.py to config.cpython-311.pyc\n",
            "byte-compiling build/bdist.linux-x86_64/egg/iiif_prezi3/config/__init__.py to __init__.cpython-311.pyc\n",
            "byte-compiling build/bdist.linux-x86_64/egg/iiif_prezi3/skeleton.py to skeleton.cpython-311.pyc\n",
            "creating build/bdist.linux-x86_64/egg/EGG-INFO\n",
            "copying iiif_prezi3.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO\n",
            "copying iiif_prezi3.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO\n",
            "copying iiif_prezi3.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO\n",
            "copying iiif_prezi3.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO\n",
            "copying iiif_prezi3.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO\n",
            "zip_safe flag not set; analyzing archive contents...\n",
            "iiif_prezi3.__pycache__.loader.cpython-311: module references __file__\n",
            "creating dist\n",
            "creating 'dist/iiif_prezi3-2.0.1-py3.11.egg' and adding 'build/bdist.linux-x86_64/egg' to it\n",
            "removing 'build/bdist.linux-x86_64/egg' (and everything under it)\n",
            "Processing iiif_prezi3-2.0.1-py3.11.egg\n",
            "creating /usr/local/lib/python3.11/dist-packages/iiif_prezi3-2.0.1-py3.11.egg\n",
            "Extracting iiif_prezi3-2.0.1-py3.11.egg to /usr/local/lib/python3.11/dist-packages\n",
            "Adding iiif-prezi3 2.0.1 to easy-install.pth file\n",
            "\n",
            "Installed /usr/local/lib/python3.11/dist-packages/iiif_prezi3-2.0.1-py3.11.egg\n",
            "Processing dependencies for iiif-prezi3==2.0.1\n",
            "Searching for pillow==11.2.1\n",
            "Best match: pillow 11.2.1\n",
            "Adding pillow 11.2.1 to easy-install.pth file\n",
            "detected new path './iiif_prezi3-2.0.1-py3.11.egg'\n",
            "\n",
            "Using /usr/local/lib/python3.11/dist-packages\n",
            "Searching for requests==2.32.3\n",
            "Best match: requests 2.32.3\n",
            "Adding requests 2.32.3 to easy-install.pth file\n",
            "\n",
            "Using /usr/local/lib/python3.11/dist-packages\n",
            "Searching for pydantic==2.11.5\n",
            "Best match: pydantic 2.11.5\n",
            "Adding pydantic 2.11.5 to easy-install.pth file\n",
            "\n",
            "Using /usr/local/lib/python3.11/dist-packages\n",
            "Searching for certifi==2025.4.26\n",
            "Best match: certifi 2025.4.26\n",
            "Adding certifi 2025.4.26 to easy-install.pth file\n",
            "\n",
            "Using /usr/local/lib/python3.11/dist-packages\n",
            "Searching for urllib3==2.4.0\n",
            "Best match: urllib3 2.4.0\n",
            "Adding urllib3 2.4.0 to easy-install.pth file\n",
            "\n",
            "Using /usr/local/lib/python3.11/dist-packages\n",
            "Searching for idna==3.10\n",
            "Best match: idna 3.10\n",
            "Adding idna 3.10 to easy-install.pth file\n",
            "\n",
            "Using /usr/local/lib/python3.11/dist-packages\n",
            "Searching for charset-normalizer==3.4.2\n",
            "Best match: charset-normalizer 3.4.2\n",
            "Adding charset-normalizer 3.4.2 to easy-install.pth file\n",
            "Installing normalizer script to /usr/local/bin\n",
            "\n",
            "Using /usr/local/lib/python3.11/dist-packages\n",
            "Searching for typing-inspection==0.4.0\n",
            "Best match: typing-inspection 0.4.0\n",
            "Adding typing-inspection 0.4.0 to easy-install.pth file\n",
            "\n",
            "Using /usr/local/lib/python3.11/dist-packages\n",
            "Searching for typing-extensions==4.13.2\n",
            "Best match: typing-extensions 4.13.2\n",
            "Adding typing-extensions 4.13.2 to easy-install.pth file\n",
            "\n",
            "Using /usr/local/lib/python3.11/dist-packages\n",
            "Searching for pydantic-core==2.33.2\n",
            "Best match: pydantic-core 2.33.2\n",
            "Adding pydantic-core 2.33.2 to easy-install.pth file\n",
            "\n",
            "Using /usr/local/lib/python3.11/dist-packages\n",
            "Searching for annotated-types==0.7.0\n",
            "Best match: annotated-types 0.7.0\n",
            "Adding annotated-types 0.7.0 to easy-install.pth file\n",
            "\n",
            "Using /usr/local/lib/python3.11/dist-packages\n",
            "Finished processing dependencies for iiif-prezi3==2.0.1\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "3seGX6NtDN7o"
      },
      "execution_count": 4,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "## テスト"
      ],
      "metadata": {
        "id": "ZJ8A8gkODOGv"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "!pip install 'pyproject-api>=1.8' 'packaging<25,>=24.2'"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "ugXwkPV5FIjw",
        "outputId": "647b93cb-a039-4388-d3a1-e1500d07b08a"
      },
      "execution_count": 5,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\u001b[33mDEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/iiif_prezi3-2.0.1-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330\u001b[0m\u001b[33m\n",
            "\u001b[0mCollecting pyproject-api>=1.8\n",
            "  Downloading pyproject_api-1.9.1-py3-none-any.whl.metadata (2.7 kB)\n",
            "Requirement already satisfied: packaging<25,>=24.2 in /usr/local/lib/python3.11/dist-packages (24.2)\n",
            "INFO: pip is looking at multiple versions of pyproject-api to determine which version is compatible with other requirements. This could take a while.\n",
            "  Downloading pyproject_api-1.9.0-py3-none-any.whl.metadata (2.7 kB)\n",
            "Downloading pyproject_api-1.9.0-py3-none-any.whl (13 kB)\n",
            "Installing collected packages: pyproject-api\n",
            "Successfully installed pyproject-api-1.9.0\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "%cd /content/iiif-prezi3\n",
        "!pip install tox\n",
        "!tox"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "CvkubnzRCmQN",
        "outputId": "873dea80-7bea-4511-a339-b860486e1c38"
      },
      "execution_count": 6,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "/content/iiif-prezi3\n",
            "\u001b[33mDEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/iiif_prezi3-2.0.1-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330\u001b[0m\u001b[33m\n",
            "\u001b[0mCollecting tox\n",
            "  Downloading tox-4.26.0-py3-none-any.whl.metadata (3.7 kB)\n",
            "Requirement already satisfied: cachetools>=5.5.1 in /usr/local/lib/python3.11/dist-packages (from tox) (5.5.2)\n",
            "Requirement already satisfied: chardet>=5.2 in /usr/local/lib/python3.11/dist-packages (from tox) (5.2.0)\n",
            "Collecting colorama>=0.4.6 (from tox)\n",
            "  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)\n",
            "Requirement already satisfied: filelock>=3.16.1 in /usr/local/lib/python3.11/dist-packages (from tox) (3.18.0)\n",
            "Requirement already satisfied: packaging>=24.2 in /usr/local/lib/python3.11/dist-packages (from tox) (24.2)\n",
            "Requirement already satisfied: platformdirs>=4.3.6 in /usr/local/lib/python3.11/dist-packages (from tox) (4.3.8)\n",
            "Requirement already satisfied: pluggy>=1.5 in /usr/local/lib/python3.11/dist-packages (from tox) (1.5.0)\n",
            "Requirement already satisfied: pyproject-api>=1.8 in /usr/local/lib/python3.11/dist-packages (from tox) (1.9.0)\n",
            "Collecting virtualenv>=20.31 (from tox)\n",
            "  Downloading virtualenv-20.31.2-py3-none-any.whl.metadata (4.5 kB)\n",
            "Collecting distlib<1,>=0.3.7 (from virtualenv>=20.31->tox)\n",
            "  Downloading distlib-0.3.9-py2.py3-none-any.whl.metadata (5.2 kB)\n",
            "Downloading tox-4.26.0-py3-none-any.whl (172 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m172.8/172.8 kB\u001b[0m \u001b[31m5.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)\n",
            "Downloading virtualenv-20.31.2-py3-none-any.whl (6.1 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m6.1/6.1 MB\u001b[0m \u001b[31m73.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading distlib-0.3.9-py2.py3-none-any.whl (468 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m469.0/469.0 kB\u001b[0m \u001b[31m31.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hInstalling collected packages: distlib, virtualenv, colorama, tox\n",
            "Successfully installed colorama-0.4.6 distlib-0.3.9 tox-4.26.0 virtualenv-20.31.2\n",
            "\u001b[1m\u001b[35mpy39:\u001b[0m\u001b[36m skipped because could not find python interpreter with spec(s): py39\u001b[0m\n",
            "\u001b[33mpy39: SKIP ⚠ in 0.28 seconds\u001b[39m\n",
            "\u001b[1m\u001b[35mpy310:\u001b[0m\u001b[36m Tox core option 'requires' is missing or does not specify keyrings.google-artifactregistry-auth. Package will not be installed in testenv\u001b[0m\n",
            "\u001b[1m\u001b[35m.pkg:\u001b[0m\u001b[36m Tox core option 'requires' is missing or does not specify keyrings.google-artifactregistry-auth. Package will not be installed in testenv\u001b[0m\n",
            "\u001b[1m\u001b[35m.pkg:\u001b[0m\u001b[36m install_requires\u001b[22m\u001b[2m>\u001b[0m python -I -m pip install 'setuptools>=40.8.0' wheel\u001b[0m\n",
            "\u001b[1m\u001b[35m.pkg:\u001b[0m\u001b[36m Tox core option 'requires' is missing or does not specify keyrings.google-artifactregistry-auth. Package will not be installed in testenv\u001b[0m\n",
            "\u001b[1m\u001b[35m.pkg:\u001b[0m\u001b[36m _optional_hooks\u001b[22m\u001b[2m>\u001b[0m python /usr/local/lib/python3.11/dist-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__\u001b[0m\n",
            "\u001b[1m\u001b[35m.pkg:\u001b[0m\u001b[36m get_requires_for_build_sdist\u001b[22m\u001b[2m>\u001b[0m python /usr/local/lib/python3.11/dist-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__\u001b[0m\n",
            "\u001b[1m\u001b[35m.pkg:\u001b[0m\u001b[36m Tox core option 'requires' is missing or does not specify keyrings.google-artifactregistry-auth. Package will not be installed in testenv\u001b[0m\n",
            "\u001b[1m\u001b[35m.pkg:\u001b[0m\u001b[36m get_requires_for_build_wheel\u001b[22m\u001b[2m>\u001b[0m python /usr/local/lib/python3.11/dist-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__\u001b[0m\n",
            "\u001b[1m\u001b[35m.pkg:\u001b[0m\u001b[36m Tox core option 'requires' is missing or does not specify keyrings.google-artifactregistry-auth. Package will not be installed in testenv\u001b[0m\n",
            "\u001b[1m\u001b[35m.pkg:\u001b[0m\u001b[36m prepare_metadata_for_build_wheel\u001b[22m\u001b[2m>\u001b[0m python /usr/local/lib/python3.11/dist-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__\u001b[0m\n",
            "\u001b[1m\u001b[35m.pkg:\u001b[0m\u001b[36m build_sdist\u001b[22m\u001b[2m>\u001b[0m python /usr/local/lib/python3.11/dist-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__\u001b[0m\n",
            "\u001b[1m\u001b[35mpy310:\u001b[0m\u001b[36m Tox core option 'requires' is missing or does not specify keyrings.google-artifactregistry-auth. Package will not be installed in testenv\u001b[0m\n",
            "\u001b[1m\u001b[35mpy310:\u001b[0m\u001b[36m install_package_deps\u001b[22m\u001b[2m>\u001b[0m python -I -m pip install 'Pillow<=12.0.0,>=9.1.1' 'pydantic<3.0.0,>=1.9.2' 'requests<3.0.0,>=2.28.0'\u001b[0m\n",
            "\u001b[1m\u001b[35mpy310:\u001b[0m\u001b[36m install_package\u001b[22m\u001b[2m>\u001b[0m python -I -m pip install --force-reinstall --no-deps /content/iiif-prezi3/.tox/.tmp/package/1/iiif_prezi3-2.0.1.tar.gz\u001b[0m\n",
            "\u001b[1m\u001b[35mpy310:\u001b[0m\u001b[36m commands[0]\u001b[22m\u001b[2m>\u001b[0m python -m unittest discover -s tests\u001b[0m\n",
            "\u001b[31m/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n",
            "* 'allow_population_by_field_name' has been renamed to 'validate_by_name'\n",
            "* 'validate_all' has been renamed to 'validate_default'\n",
            "* 'copy_on_model_validation' has been removed\n",
            "* 'smart_union' has been removed\n",
            "  warnings.warn(message, UserWarning)\n",
            "\u001b[39m\u001b[31m/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n",
            "* 'allow_population_by_field_name' has been renamed to 'validate_by_name'\n",
            "* 'validate_all' has been renamed to 'validate_default'\n",
            "* 'copy_on_model_validation' has been removed\n",
            "* 'smart_union' has been removed\n",
            "  warnings.warn(message, UserWarning)\n",
            "\u001b[39m\u001b[31mEEEEEEEEEEEEEEEEEEEE\n",
            "======================================================================\n",
            "ERROR: test_add_item (unittest.loader._FailedTest)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_add_item\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 436, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 377, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_add_item.py\", line 5, in <module>\n",
            "    from iiif_prezi3 import (AccompanyingCanvas, Annotation, AnnotationPage,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "\u001b[39m\u001b[31m    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "    private_attributes = inspect_namespace(\n",
            "  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "======================================================================\n",
            "ERROR: test_add_metadata (unittest.loader._FailedTest)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_add_metadata\n",
            "Traceback (most recent call last):\n",
            "\u001b[39m\u001b[31m  File \"/usr/lib/python3.10/unittest/loader.py\", line 436, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 377, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_add_metadata.py\", line 3, in <module>\n",
            "    from iiif_prezi3 import Collection, LngString\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "\u001b[39m\u001b[31m    private_attributes = inspect_namespace(\n",
            "  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "======================================================================\n",
            "ERROR: test_add_range (unittest.loader._FailedTest)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_add_range\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 436, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 377, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_add_range.py\", line 3, in <module>\n",
            "    from iiif_prezi3 import Manifest, Range\n",
            "\u001b[39m\u001b[31m  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "    private_attributes = inspect_namespace(\n",
            "  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "\u001b[39m\u001b[31mTypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "======================================================================\n",
            "ERROR: test_add_service (unittest.loader._FailedTest)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_add_service\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 436, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 377, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_add_service.py\", line 3, in <module>\n",
            "    from iiif_prezi3 import (Annotation, AnnotationCollection, AnnotationPage,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "\u001b[39m\u001b[31m  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "    private_attributes = inspect_namespace(\n",
            "  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "======================================================================\n",
            "ERROR: test_add_thumbnail (unittest.loader._FailedTest)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_add_thumbnail\n",
            "\u001b[39m\u001b[31mTraceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 436, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 377, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_add_thumbnail.py\", line 4, in <module>\n",
            "    from iiif_prezi3 import Manifest\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "\u001b[39m\u001b[31m  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "    private_attributes = inspect_namespace(\n",
            "  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "======================================================================\n",
            "ERROR: test_annotation_helpers (unittest.loader._FailedTest)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_annotation_helpers\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 436, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 377, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_annotation_helpers.py\", line 3, in <module>\n",
            "\u001b[39m\u001b[31m    from iiif_prezi3 import Annotation, AnnotationPage, Manifest\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "    private_attributes = inspect_namespace(\n",
            "  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "\u001b[39m\u001b[31m    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "======================================================================\n",
            "ERROR: test_basic (unittest.loader._FailedTest)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_basic\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 436, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 377, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_basic.py\", line 7, in <module>\n",
            "    from iiif_prezi3 import Canvas, Manifest\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "\u001b[39m\u001b[31m  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "    private_attributes = inspect_namespace(\n",
            "  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "======================================================================\n",
            "ERROR: test_canvas_helpers (unittest.loader._FailedTest)\n",
            "----------------------------------------------------------------------\n",
            "\u001b[39m\u001b[31mImportError: Failed to import test module: test_canvas_helpers\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 436, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 377, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_canvas_helpers.py\", line 3, in <module>\n",
            "    from iiif_prezi3 import AnnotationPage, Canvas, ResourceItem\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "\u001b[39m\u001b[31m  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "    private_attributes = inspect_namespace(\n",
            "  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "======================================================================\n",
            "ERROR: test_create_canvas_from_iiif (unittest.loader._FailedTest)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_create_canvas_from_iiif\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 436, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 377, in _get_module_from_name\n",
            "    __import__(name)\n",
            "\u001b[39m\u001b[31m  File \"/content/iiif-prezi3/tests/test_create_canvas_from_iiif.py\", line 4, in <module>\n",
            "    from iiif_prezi3 import Manifest\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "    private_attributes = inspect_namespace(\n",
            "  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "\u001b[39m\u001b[31m    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\u001b[39m\u001b[31m\n",
            "======================================================================\n",
            "ERROR: test_extensions (unittest.loader._FailedTest)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_extensions\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 436, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 377, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_extensions.py\", line 4, in <module>\n",
            "    import iiif_prezi3\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "\u001b[39m\u001b[31m    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "    private_attributes = inspect_namespace(\n",
            "  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "======================================================================\n",
            "ERROR: test_helpers_addlabel (unittest.loader._FailedTest)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_helpers_addlabel\n",
            "Traceback (most recent call last):\n",
            "\u001b[39m\u001b[31m  File \"/usr/lib/python3.10/unittest/loader.py\", line 436, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 377, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_helpers_addlabel.py\", line 3, in <module>\n",
            "    from iiif_prezi3 import Canvas, config\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "    private_attributes = inspect_namespace(\n",
            "\u001b[39m\u001b[31m  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "======================================================================\n",
            "ERROR: test_helpers_autofields (unittest.loader._FailedTest)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_helpers_autofields\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 436, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 377, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_helpers_autofields.py\", line 3, in <module>\n",
            "    from iiif_prezi3 import Collection, Manifest, config\n",
            "\u001b[39m\u001b[31m  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "    private_attributes = inspect_namespace(\n",
            "  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "\u001b[39m\u001b[31mTypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "======================================================================\n",
            "ERROR: test_make_canvas (unittest.loader._FailedTest)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_make_canvas\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 436, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 377, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_make_canvas.py\", line 3, in <module>\n",
            "    from iiif_prezi3 import Canvas, Manifest\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "\u001b[39m\u001b[31m    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "    private_attributes = inspect_namespace(\n",
            "  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "======================================================================\n",
            "ERROR: test_make_collection (unittest.loader._FailedTest)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_make_collection\n",
            "Traceback (most recent call last):\n",
            "\u001b[39m\u001b[31m  File \"/usr/lib/python3.10/unittest/loader.py\", line 436, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 377, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_make_collection.py\", line 3, in <module>\n",
            "    from iiif_prezi3 import Collection\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "\u001b[39m\u001b[31m    private_attributes = inspect_namespace(\n",
            "  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "======================================================================\n",
            "ERROR: test_make_manifest (unittest.loader._FailedTest)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_make_manifest\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 436, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 377, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_make_manifest.py\", line 3, in <module>\n",
            "\u001b[39m\u001b[31m    from iiif_prezi3 import Collection, HomepageItem, Reference, config\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "    private_attributes = inspect_namespace(\n",
            "  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "\u001b[39m\u001b[31mTypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "======================================================================\n",
            "ERROR: test_make_range (unittest.loader._FailedTest)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_make_range\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 436, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 377, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_make_range.py\", line 3, in <module>\n",
            "    from iiif_prezi3 import Manifest, Range\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "\u001b[39m\u001b[31m  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "    private_attributes = inspect_namespace(\n",
            "  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "======================================================================\n",
            "ERROR: test_make_service (unittest.loader._FailedTest)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_make_service\n",
            "\u001b[39m\u001b[31mTraceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 436, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 377, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_make_service.py\", line 3, in <module>\n",
            "    from iiif_prezi3 import (Annotation, AnnotationCollection, AnnotationPage,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "\u001b[39m\u001b[31m  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "    private_attributes = inspect_namespace(\n",
            "  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\u001b[39m\u001b[31m\n",
            "======================================================================\n",
            "ERROR: test_set_hwd (unittest.loader._FailedTest)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_set_hwd\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 436, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 377, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_set_hwd.py\", line 6, in <module>\n",
            "    from iiif_prezi3 import Canvas\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "\u001b[39m\u001b[31m    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "    private_attributes = inspect_namespace(\n",
            "  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "======================================================================\n",
            "ERROR: test_set_hwd_from_file_helper (unittest.loader._FailedTest)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_set_hwd_from_file_helper\n",
            "Traceback (most recent call last):\n",
            "\u001b[39m\u001b[31m  File \"/usr/lib/python3.10/unittest/loader.py\", line 436, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 377, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_set_hwd_from_file_helper.py\", line 3, in <module>\n",
            "    from iiif_prezi3 import Canvas\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "    private_attributes = inspect_namespace(\n",
            "\u001b[39m\u001b[31m  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "======================================================================\n",
            "ERROR: test_set_hwd_from_iiif (unittest.loader._FailedTest)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_set_hwd_from_iiif\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 436, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 377, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_set_hwd_from_iiif.py\", line 6, in <module>\n",
            "    from iiif_prezi3 import Canvas\n",
            "\u001b[39m\u001b[31m  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "    private_attributes = inspect_namespace(\n",
            "  File \"/content/iiif-prezi3/.tox/py310/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "\u001b[39m\u001b[31mTypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "----------------------------------------------------------------------\n",
            "Ran 20 tests in 0.004s\n",
            "\n",
            "FAILED (errors=20)\n",
            "\u001b[39m\u001b[1m\u001b[35mpy310:\u001b[0m\u001b[31m exit 1 (0.58 seconds) /content/iiif-prezi3> python -m unittest discover -s tests pid=721\u001b[0m\n",
            "\u001b[31mpy310: FAIL ✖ in 21.3 seconds\u001b[39m\n",
            "\u001b[1m\u001b[35mpy311:\u001b[0m\u001b[36m Tox core option 'requires' is missing or does not specify keyrings.google-artifactregistry-auth. Package will not be installed in testenv\u001b[0m\n",
            "\u001b[1m\u001b[35mpy311:\u001b[0m\u001b[36m Tox core option 'requires' is missing or does not specify keyrings.google-artifactregistry-auth. Package will not be installed in testenv\u001b[0m\n",
            "\u001b[1m\u001b[35mpy311:\u001b[0m\u001b[36m install_package_deps\u001b[22m\u001b[2m>\u001b[0m python -I -m pip install 'Pillow<=12.0.0,>=9.1.1' 'pydantic<3.0.0,>=1.9.2' 'requests<3.0.0,>=2.28.0'\u001b[0m\n",
            "\u001b[1m\u001b[35mpy311:\u001b[0m\u001b[36m install_package\u001b[22m\u001b[2m>\u001b[0m python -I -m pip install --force-reinstall --no-deps /content/iiif-prezi3/.tox/.tmp/package/2/iiif_prezi3-2.0.1.tar.gz\u001b[0m\n",
            "\u001b[1m\u001b[35mpy311:\u001b[0m\u001b[36m commands[0]\u001b[22m\u001b[2m>\u001b[0m python -m unittest discover -s tests\u001b[0m\n",
            "\u001b[31m/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n",
            "* 'allow_population_by_field_name' has been renamed to 'validate_by_name'\n",
            "* 'validate_all' has been renamed to 'validate_default'\n",
            "* 'copy_on_model_validation' has been removed\n",
            "* 'smart_union' has been removed\n",
            "  warnings.warn(message, UserWarning)\n",
            "\u001b[39m\u001b[31m/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n",
            "* 'allow_population_by_field_name' has been renamed to 'validate_by_name'\n",
            "* 'validate_all' has been renamed to 'validate_default'\n",
            "* 'copy_on_model_validation' has been removed\n",
            "* 'smart_union' has been removed\n",
            "  warnings.warn(message, UserWarning)\n",
            "\u001b[39m\u001b[31mEEEEEEEEEEEEEEEEEEEE\n",
            "\u001b[39m\u001b[31m======================================================================\n",
            "ERROR: test_add_item (unittest.loader._FailedTest.test_add_item)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_add_item\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 419, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 362, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_add_item.py\", line 5, in <module>\n",
            "    from iiif_prezi3 import (AccompanyingCanvas, Annotation, AnnotationPage,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "\u001b[39m\u001b[31m    from .add_image import AddImage  # noqa: F401\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "    private_attributes = inspect_namespace(\n",
            "                         ^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "======================================================================\n",
            "\u001b[39m\u001b[31mERROR: test_add_metadata (unittest.loader._FailedTest.test_add_metadata)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_add_metadata\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 419, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 362, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_add_metadata.py\", line 3, in <module>\n",
            "    from iiif_prezi3 import Collection, LngString\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "\u001b[39m\u001b[31m    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "    private_attributes = inspect_namespace(\n",
            "                         ^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "======================================================================\n",
            "ERROR: test_add_range (unittest.loader._FailedTest.test_add_range)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_add_range\n",
            "\u001b[39m\u001b[31mTraceback (most recent call last):\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 419, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 362, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_add_range.py\", line 3, in <module>\n",
            "    from iiif_prezi3 import Manifest, Range\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "\u001b[39m\u001b[31m  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "    private_attributes = inspect_namespace(\n",
            "                         ^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "======================================================================\n",
            "ERROR: test_add_service (unittest.loader._FailedTest.test_add_service)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_add_service\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 419, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "\u001b[39m\u001b[31m             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 362, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_add_service.py\", line 3, in <module>\n",
            "    from iiif_prezi3 import (Annotation, AnnotationCollection, AnnotationPage,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "\u001b[39m\u001b[31m    private_attributes = inspect_namespace(\n",
            "                         ^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "======================================================================\n",
            "ERROR: test_add_thumbnail (unittest.loader._FailedTest.test_add_thumbnail)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_add_thumbnail\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 419, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 362, in _get_module_from_name\n",
            "\u001b[39m\u001b[31m    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_add_thumbnail.py\", line 4, in <module>\n",
            "    from iiif_prezi3 import Manifest\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "    private_attributes = inspect_namespace(\n",
            "                         ^^^^^^^^^^^^^^^^^^\n",
            "\u001b[39m\u001b[31m  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "======================================================================\n",
            "ERROR: test_annotation_helpers (unittest.loader._FailedTest.test_annotation_helpers)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_annotation_helpers\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 419, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 362, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_annotation_helpers.py\", line 3, in <module>\n",
            "\u001b[39m\u001b[31m    from iiif_prezi3 import Annotation, AnnotationPage, Manifest\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "    private_attributes = inspect_namespace(\n",
            "                         ^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "\u001b[39m\u001b[31m    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "======================================================================\n",
            "ERROR: test_basic (unittest.loader._FailedTest.test_basic)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_basic\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 419, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 362, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_basic.py\", line 7, in <module>\n",
            "    from iiif_prezi3 import Canvas, Manifest\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "\u001b[39m\u001b[31m  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "    private_attributes = inspect_namespace(\n",
            "                         ^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "\u001b[39m\u001b[31m======================================================================\n",
            "ERROR: test_canvas_helpers (unittest.loader._FailedTest.test_canvas_helpers)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_canvas_helpers\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 419, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 362, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_canvas_helpers.py\", line 3, in <module>\n",
            "\u001b[39m\u001b[31m    from iiif_prezi3 import AnnotationPage, Canvas, ResourceItem\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "    private_attributes = inspect_namespace(\n",
            "                         ^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "\u001b[39m\u001b[31m    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "======================================================================\n",
            "ERROR: test_create_canvas_from_iiif (unittest.loader._FailedTest.test_create_canvas_from_iiif)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_create_canvas_from_iiif\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 419, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 362, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_create_canvas_from_iiif.py\", line 4, in <module>\n",
            "    from iiif_prezi3 import Manifest\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "\u001b[39m\u001b[31m    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "    private_attributes = inspect_namespace(\n",
            "                         ^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "\u001b[39m\u001b[31mTypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "======================================================================\n",
            "ERROR: test_extensions (unittest.loader._FailedTest.test_extensions)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_extensions\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 419, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 362, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_extensions.py\", line 4, in <module>\n",
            "    import iiif_prezi3\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "\u001b[39m\u001b[31m    from .add_image import AddImage  # noqa: F401\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "    private_attributes = inspect_namespace(\n",
            "                         ^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "======================================================================\n",
            "\u001b[39m\u001b[31mERROR: test_helpers_addlabel (unittest.loader._FailedTest.test_helpers_addlabel)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_helpers_addlabel\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 419, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 362, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_helpers_addlabel.py\", line 3, in <module>\n",
            "    from iiif_prezi3 import Canvas, config\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "\u001b[39m\u001b[31m    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "    private_attributes = inspect_namespace(\n",
            "                         ^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "======================================================================\n",
            "ERROR: test_helpers_autofields (unittest.loader._FailedTest.test_helpers_autofields)\n",
            "----------------------------------------------------------------------\n",
            "\u001b[39m\u001b[31mImportError: Failed to import test module: test_helpers_autofields\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 419, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 362, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_helpers_autofields.py\", line 3, in <module>\n",
            "    from iiif_prezi3 import Collection, Manifest, config\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "\u001b[39m\u001b[31m  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "    private_attributes = inspect_namespace(\n",
            "                         ^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "======================================================================\n",
            "ERROR: test_make_canvas (unittest.loader._FailedTest.test_make_canvas)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_make_canvas\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 419, in _find_test_path\n",
            "\u001b[39m\u001b[31m    module = self._get_module_from_name(name)\n",
            "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 362, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_make_canvas.py\", line 3, in <module>\n",
            "    from iiif_prezi3 import Canvas, Manifest\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "\u001b[39m\u001b[31m  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "    private_attributes = inspect_namespace(\n",
            "                         ^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "======================================================================\n",
            "ERROR: test_make_collection (unittest.loader._FailedTest.test_make_collection)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_make_collection\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 419, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "\u001b[39m\u001b[31m  File \"/usr/lib/python3.11/unittest/loader.py\", line 362, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_make_collection.py\", line 3, in <module>\n",
            "    from iiif_prezi3 import Collection\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "    private_attributes = inspect_namespace(\n",
            "                         ^^^^^^^^^^^^^^^^^^\n",
            "\u001b[39m\u001b[31m  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "======================================================================\n",
            "ERROR: test_make_manifest (unittest.loader._FailedTest.test_make_manifest)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_make_manifest\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 419, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 362, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_make_manifest.py\", line 3, in <module>\n",
            "\u001b[39m\u001b[31m    from iiif_prezi3 import Collection, HomepageItem, Reference, config\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "    private_attributes = inspect_namespace(\n",
            "                         ^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "\u001b[39m\u001b[31m    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "======================================================================\n",
            "ERROR: test_make_range (unittest.loader._FailedTest.test_make_range)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_make_range\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 419, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 362, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_make_range.py\", line 3, in <module>\n",
            "    from iiif_prezi3 import Manifest, Range\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "\u001b[39m\u001b[31m    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "    private_attributes = inspect_namespace(\n",
            "                         ^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "\u001b[39m\u001b[31mTypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "======================================================================\n",
            "ERROR: test_make_service (unittest.loader._FailedTest.test_make_service)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_make_service\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 419, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "\u001b[39m\u001b[31m             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 362, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_make_service.py\", line 3, in <module>\n",
            "    from iiif_prezi3 import (Annotation, AnnotationCollection, AnnotationPage,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "\u001b[39m\u001b[31m    private_attributes = inspect_namespace(\n",
            "                         ^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "======================================================================\n",
            "ERROR: test_set_hwd (unittest.loader._FailedTest.test_set_hwd)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_set_hwd\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 419, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 362, in _get_module_from_name\n",
            "    __import__(name)\n",
            "\u001b[39m\u001b[31m  File \"/content/iiif-prezi3/tests/test_set_hwd.py\", line 6, in <module>\n",
            "    from iiif_prezi3 import Canvas\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "    private_attributes = inspect_namespace(\n",
            "                         ^^^^^^^^^^^^^^^^^^\n",
            "\u001b[39m\u001b[31m  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "======================================================================\n",
            "ERROR: test_set_hwd_from_file_helper (unittest.loader._FailedTest.test_set_hwd_from_file_helper)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_set_hwd_from_file_helper\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 419, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 362, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_set_hwd_from_file_helper.py\", line 3, in <module>\n",
            "    from iiif_prezi3 import Canvas\n",
            "\u001b[39m\u001b[31m  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "    private_attributes = inspect_namespace(\n",
            "                         ^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "\u001b[39m\u001b[31m    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "======================================================================\n",
            "ERROR: test_set_hwd_from_iiif (unittest.loader._FailedTest.test_set_hwd_from_iiif)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: test_set_hwd_from_iiif\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 419, in _find_test_path\n",
            "    module = self._get_module_from_name(name)\n",
            "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/lib/python3.11/unittest/loader.py\", line 362, in _get_module_from_name\n",
            "    __import__(name)\n",
            "  File \"/content/iiif-prezi3/tests/test_set_hwd_from_iiif.py\", line 6, in <module>\n",
            "    from iiif_prezi3 import Canvas\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/__init__.py\", line 1, in <module>\n",
            "    from iiif_prezi3.helpers import *  # noqa: F401,F403\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "\u001b[39m\u001b[31m  File \"/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\", line 1, in <module>\n",
            "    from .add_image import AddImage  # noqa: F401\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\", line 2, in <module>\n",
            "    from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n",
            "  File \"/content/iiif-prezi3/iiif_prezi3/skeleton.py\", line 15, in <module>\n",
            "    class Behavior(Base):\n",
            "  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 112, in __new__\n",
            "    private_attributes = inspect_namespace(\n",
            "                         ^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/iiif-prezi3/.tox/py311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py\", line 402, in inspect_namespace\n",
            "    raise TypeError(\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\")\n",
            "TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'\n",
            "\n",
            "\n",
            "\u001b[39m\u001b[31m----------------------------------------------------------------------\n",
            "Ran 20 tests in 0.002s\n",
            "\n",
            "FAILED (errors=20)\n",
            "\u001b[39m\u001b[1m\u001b[35mpy311:\u001b[0m\u001b[31m exit 1 (0.58 seconds) /content/iiif-prezi3> python -m unittest discover -s tests pid=853\u001b[0m\n",
            "\u001b[31mpy311: FAIL ✖ in 13.65 seconds\u001b[39m\n",
            "\u001b[1m\u001b[35mlinting:\u001b[0m\u001b[36m Tox core option 'requires' is missing or does not specify keyrings.google-artifactregistry-auth. Package will not be installed in testenv\u001b[0m\n",
            "\u001b[1m\u001b[35mlinting:\u001b[0m\u001b[36m Tox core option 'requires' is missing or does not specify keyrings.google-artifactregistry-auth. Package will not be installed in testenv\u001b[0m\n",
            "\u001b[1m\u001b[35mlinting:\u001b[0m\u001b[36m install_package_deps\u001b[22m\u001b[2m>\u001b[0m python -I -m pip install 'Pillow<=12.0.0,>=9.1.1' 'autopep8<3.0.0,>=1.6.0' 'datamodel-code-generator<1.0.0,>=0.17.1' 'deepdiff<9.0.0,>=6.2.2' 'flake8-docstrings<2.0.0,>=1.6.0' 'flake8-isort<7.0.0,>=4.1.1' 'flake8<8.0.0,>=7.2.0' 'isort<6.0.0,>=5.10.1' 'pydantic<3.0.0,>=1.9.2' 'requests<3.0.0,>=2.28.0' 'tox<5.0.0,>=3.25.0'\u001b[0m\n",
            "\u001b[1m\u001b[35mlinting:\u001b[0m\u001b[36m install_package\u001b[22m\u001b[2m>\u001b[0m python -I -m pip install --force-reinstall --no-deps /content/iiif-prezi3/.tox/.tmp/package/3/iiif_prezi3-2.0.1.tar.gz\u001b[0m\n",
            "\u001b[1m\u001b[35mlinting:\u001b[0m\u001b[36m commands[0]\u001b[22m\u001b[2m>\u001b[0m isort .\u001b[0m\n",
            "Skipped 4 files\n",
            "\u001b[1m\u001b[35mlinting:\u001b[0m\u001b[36m commands[1]\u001b[22m\u001b[2m>\u001b[0m autopep8 --in-place --recursive --exclude skeleton.py --ignore E501 .\u001b[0m\n",
            "\u001b[1m\u001b[35mlinting:\u001b[0m\u001b[36m commands[2]\u001b[22m\u001b[2m>\u001b[0m flake8\u001b[0m\n",
            "\u001b[32mlinting: OK ✔ in 24.75 seconds\u001b[39m\n",
            "\u001b[1m\u001b[35mpy312:\u001b[0m\u001b[36m skipped because could not find python interpreter with spec(s): py312\u001b[0m\n",
            "\u001b[33mpy312: SKIP ⚠ in 0.01 seconds\u001b[39m\n",
            "\u001b[1m\u001b[35mpy313:\u001b[0m\u001b[36m skipped because could not find python interpreter with spec(s): py313\u001b[0m\n",
            "\u001b[33m  py39: SKIP (0.28 seconds)\u001b[39m\n",
            "\u001b[31m  py310: FAIL code 1 (21.30=setup[20.72]+cmd[0.58] seconds)\u001b[39m\n",
            "\u001b[31m  py311: FAIL code 1 (13.65=setup[13.06]+cmd[0.58] seconds)\u001b[39m\n",
            "\u001b[32m  linting: OK (24.75=setup[21.70]+cmd[0.23,1.75,1.08] seconds)\u001b[39m\n",
            "\u001b[33m  py312: SKIP (0.01 seconds)\u001b[39m\n",
            "\u001b[33m  py313: SKIP (0.01 seconds)\u001b[39m\n",
            "\u001b[31m  evaluation failed :( (60.18 seconds)\u001b[39m\n",
            "\u001b[0m"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "pk_sGNMfDQM0"
      },
      "execution_count": 6,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "## 使ってみる（失敗する）"
      ],
      "metadata": {
        "id": "5tY9id5UIaOJ"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "from iiif_prezi3 import Manifest"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 410
        },
        "id": "ueg5dIXaIhb4",
        "outputId": "bdce32e9-9166-489f-c2c7-a69a5a572c80"
      },
      "execution_count": 7,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "/usr/local/lib/python3.11/dist-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n",
            "* 'allow_population_by_field_name' has been renamed to 'validate_by_name'\n",
            "* 'validate_all' has been renamed to 'validate_default'\n",
            "* 'copy_on_model_validation' has been removed\n",
            "* 'smart_union' has been removed\n",
            "  warnings.warn(message, UserWarning)\n"
          ]
        },
        {
          "output_type": "error",
          "ename": "TypeError",
          "evalue": "To define root models, use `pydantic.RootModel` rather than a field called '__root__'",
          "traceback": [
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
            "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
            "\u001b[0;32m<ipython-input-7-707b0f25e7bd>\u001b[0m in \u001b[0;36m<cell line: 0>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0;32mfrom\u001b[0m \u001b[0miiif_prezi3\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mManifest\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
            "\u001b[0;32m/content/iiif-prezi3/iiif_prezi3/__init__.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0;32mfrom\u001b[0m \u001b[0miiif_prezi3\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mhelpers\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0;34m*\u001b[0m  \u001b[0;31m# noqa: F401,F403\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0;34m.\u001b[0m\u001b[0mloader\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mload_bundled_extensions\u001b[0m  \u001b[0;31m# noqa: F401\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0;34m.\u001b[0m\u001b[0mskeleton\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0;34m*\u001b[0m  \u001b[0;31m# noqa: F401,F403\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
            "\u001b[0;32m/content/iiif-prezi3/iiif_prezi3/helpers/__init__.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0;32mfrom\u001b[0m \u001b[0;34m.\u001b[0m\u001b[0madd_image\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mAddImage\u001b[0m  \u001b[0;31m# noqa: F401\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0;34m.\u001b[0m\u001b[0madd_item\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mAddItem\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mAddItemByReference\u001b[0m  \u001b[0;31m# noqa: F401\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0;34m.\u001b[0m\u001b[0madd_label\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mAddLabel\u001b[0m  \u001b[0;31m# noqa: F401\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0;34m.\u001b[0m\u001b[0madd_metadata\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mAddMetadata\u001b[0m  \u001b[0;31m# noqa: F401\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0;34m.\u001b[0m\u001b[0madd_range\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mAddRange\u001b[0m  \u001b[0;31m# noqa: F401\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
            "\u001b[0;32m/content/iiif-prezi3/iiif_prezi3/helpers/add_image.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0;34m.\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mloader\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mmonkeypatch_schema\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m from ..skeleton import (AccompanyingCanvas, Annotation, AnnotationPage, Canvas,\n\u001b[0m\u001b[1;32m      3\u001b[0m                         PlaceholderCanvas, ResourceItem)\n\u001b[1;32m      4\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
            "\u001b[0;32m/content/iiif-prezi3/iiif_prezi3/skeleton.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m     13\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     14\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 15\u001b[0;31m \u001b[0;32mclass\u001b[0m \u001b[0mBehavior\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mBase\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     16\u001b[0m     __root__: List[\n\u001b[1;32m     17\u001b[0m         Union[\n",
            "\u001b[0;32m/usr/local/lib/python3.11/dist-packages/pydantic/_internal/_model_construction.py\u001b[0m in \u001b[0;36m__new__\u001b[0;34m(mcs, cls_name, bases, namespace, __pydantic_generic_metadata__, __pydantic_reset_parent_namespace__, _create_model_module, **kwargs)\u001b[0m\n\u001b[1;32m    110\u001b[0m             \u001b[0mconfig_wrapper\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mConfigWrapper\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfor_model\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mbases\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mnamespace\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    111\u001b[0m             \u001b[0mnamespace\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'model_config'\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mconfig_wrapper\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mconfig_dict\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 112\u001b[0;31m             private_attributes = inspect_namespace(\n\u001b[0m\u001b[1;32m    113\u001b[0m                 \u001b[0mnamespace\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mconfig_wrapper\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mignored_types\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mclass_vars\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mbase_field_names\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    114\u001b[0m             )\n",
            "\u001b[0;32m/usr/local/lib/python3.11/dist-packages/pydantic/_internal/_model_construction.py\u001b[0m in \u001b[0;36minspect_namespace\u001b[0;34m(namespace, ignored_types, base_class_vars, base_class_fields)\u001b[0m\n\u001b[1;32m    400\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    401\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0;34m'__root__'\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mraw_annotations\u001b[0m \u001b[0;32mor\u001b[0m \u001b[0;34m'__root__'\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mnamespace\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 402\u001b[0;31m         \u001b[0;32mraise\u001b[0m \u001b[0mTypeError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"To define root models, use `pydantic.RootModel` rather than a field called '__root__'\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    403\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    404\u001b[0m     \u001b[0mignored_names\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0mset\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mstr\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mset\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
            "\u001b[0;31mTypeError\u001b[0m: To define root models, use `pydantic.RootModel` rather than a field called '__root__'"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "og5P8IhrIhmN"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "## 不要なパッケージを削除して iiif-prezi3 をインストールする"
      ],
      "metadata": {
        "id": "nCh6EuzGJAk4"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "!pip uninstall -y albumentations google-genai langchain langchain-core thinc"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "1NYNwwpCJG4i",
        "outputId": "3ae42086-5a3a-45c0-abf5-121c2228786f"
      },
      "execution_count": 8,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Found existing installation: albumentations 2.0.6\n",
            "Uninstalling albumentations-2.0.6:\n",
            "  Successfully uninstalled albumentations-2.0.6\n",
            "Found existing installation: google-genai 1.15.0\n",
            "Uninstalling google-genai-1.15.0:\n",
            "  Successfully uninstalled google-genai-1.15.0\n",
            "Found existing installation: langchain 0.3.25\n",
            "Uninstalling langchain-0.3.25:\n",
            "  Successfully uninstalled langchain-0.3.25\n",
            "Found existing installation: langchain-core 0.3.59\n",
            "Uninstalling langchain-core-0.3.59:\n",
            "  Successfully uninstalled langchain-core-0.3.59\n",
            "Found existing installation: thinc 8.3.6\n",
            "Uninstalling thinc-8.3.6:\n",
            "  Successfully uninstalled thinc-8.3.6\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "!pip uninstall -y iiif-prezi3\n",
        "!pip install iiif-prezi3"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 617
        },
        "id": "0WXZISoQJLB1",
        "outputId": "4de610db-3911-453a-cd81-74f3b4f95fff"
      },
      "execution_count": 9,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\u001b[33mDEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/iiif_prezi3-2.0.1-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330\u001b[0m\u001b[33m\n",
            "\u001b[0mFound existing installation: iiif-prezi3 2.0.1\n",
            "Uninstalling iiif-prezi3-2.0.1:\n",
            "  Successfully uninstalled iiif-prezi3-2.0.1\n",
            "Collecting iiif-prezi3\n",
            "  Using cached iiif_prezi3-2.0.1-py3-none-any.whl.metadata (8.0 kB)\n",
            "Collecting pydantic<2.0.0,>=1.9.2 (from iiif-prezi3)\n",
            "  Using cached pydantic-1.10.22-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (154 kB)\n",
            "Requirement already satisfied: requests<3.0.0,>=2.28.0 in /usr/local/lib/python3.11/dist-packages (from iiif-prezi3) (2.32.3)\n",
            "Requirement already satisfied: Pillow<=12.0.0,>=9.1.1 in /usr/local/lib/python3.11/dist-packages (from iiif-prezi3) (11.2.1)\n",
            "Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<2.0.0,>=1.9.2->iiif-prezi3) (4.13.2)\n",
            "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.28.0->iiif-prezi3) (3.4.2)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.28.0->iiif-prezi3) (3.10)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.28.0->iiif-prezi3) (2.4.0)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.28.0->iiif-prezi3) (2025.4.26)\n",
            "Using cached iiif_prezi3-2.0.1-py3-none-any.whl (28 kB)\n",
            "Using cached pydantic-1.10.22-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)\n",
            "Installing collected packages: pydantic, iiif-prezi3\n",
            "  Attempting uninstall: pydantic\n",
            "    Found existing installation: pydantic 2.11.5\n",
            "    Uninstalling pydantic-2.11.5:\n",
            "      Successfully uninstalled pydantic-2.11.5\n",
            "\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
            "google-cloud-aiplatform 1.92.0 requires google-genai<2.0.0,>=1.0.0, which is not installed.\n",
            "spacy 3.8.5 requires thinc<8.4.0,>=8.3.4, which is not installed.\u001b[0m\u001b[31m\n",
            "\u001b[0mSuccessfully installed iiif-prezi3-2.0.1 pydantic-1.10.22\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "application/vnd.colab-display-data+json": {
              "pip_warning": {
                "packages": [
                  "pydantic"
                ]
              },
              "id": "3bb1428f52cb4c6abef50dc8b65d6ae0"
            }
          },
          "metadata": {}
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "from iiif_prezi3 import Manifest\n",
        "\n",
        "m = Manifest(id=\"https://example.com/iiif/manifest.json\", label={\"en\":[\"Example Manifest\"]})\n",
        "\n",
        "print(m.json(indent=2))"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "y3M5uwrsJLHS",
        "outputId": "8f9cbbc5-ec95-47c4-f08c-d94367a5dc1a"
      },
      "execution_count": 1,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "{\n",
            "  \"@context\": \"http://iiif.io/api/presentation/3/context.json\",\n",
            "  \"id\": \"https://example.com/iiif/manifest.json\",\n",
            "  \"type\": \"Manifest\",\n",
            "  \"label\": {\n",
            "    \"en\": [\n",
            "      \"Example Manifest\"\n",
            "    ]\n",
            "  },\n",
            "  \"items\": []\n",
            "}\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "LKITqEx0Jp12"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}